# Generated by Django 5.2 on 2025-05-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='부서명')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=10, verbose_name='시작 시간')),
                ('end_time', models.CharField(max_length=10, verbose_name='종료 시간')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '시간대',
                'verbose_name_plural': '시간대',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=15, verbose_name='연락처')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='schedule.department', verbose_name='부서')),
            ],
            options={
                'verbose_name': '의사',
                'verbose_name_plural': '의사',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('weekday', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토'), ('일', '일')], max_length=10, verbose_name='요일')),
                ('is_on_call', models.BooleanField(default=False, verbose_name='당직 여부')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.doctor', verbose_name='의사')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.timeslot', verbose_name='시간대')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
                'ordering': ['date', 'time_slot__start_time'],
            },
        ),
    ]
