# Generated by Django 5.2 on 2025-05-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=10, verbose_name='시작 시간')),
                ('end_time', models.CharField(max_length=10, verbose_name='종료 시간')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '근무 시간대',
                'verbose_name_plural': '근무 시간대',
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('순환기내과', '순환기내과'), ('순환기내과 병동', '순환기내과 병동'), ('분과통합(순환기내과 제외)', '분과통합(순환기내과 제외)'), ('내과계 중환자실', '내과계 중환자실'), ('소화기내과 응급내시경(on call)', '소화기내과 응급내시경(on call)'), ('외과(ER call only)', '외과(ER call only)'), ('외과 당직의', '외과 당직의'), ('외과 수술의', '외과 수술의'), ('외과계 중환자실', '외과계 중환자실'), ('산부인과', '산부인과'), ('소아과 ER', '소아과 ER'), ('소아과 병동', '소아과 병동'), ('소아과 NICU', '소아과 NICU'), ('신경과', '신경과'), ('신경외과', '신경외과'), ('정형외과', '정형외과'), ('재활의학과', '재활의학과'), ('성형외과', '성형외과'), ('폐식도외과', '폐식도외과'), ('심장혈관외과', '심장혈관외과'), ('비뇨의학과', '비뇨의학과'), ('이비인후과(on call)', '이비인후과(on call)'), ('마취통증의학과', '마취통증의학과'), ('응급의학과', '응급의학과')], max_length=100, verbose_name='부서명'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedule.workschedule', verbose_name='근무시간'),
        ),
    ]
