# Generated by Django 5.2 on 2025-05-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_workschedule_alter_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_slot',
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'work_schedule__start_time'], 'verbose_name': '일정', 'verbose_name_plural': '일정'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.workschedule', verbose_name='근무시간'),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
