# Generated by Django 5.2 on 2025-05-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('default_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='기본 연락처')),
                ('is_on_call', models.BooleanField(default=False, verbose_name='당직 여부')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='schedule.department', verbose_name='부서')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='schedule.workschedule', verbose_name='근무시간')),
            ],
            options={
                'verbose_name': '당직 템플릿',
                'verbose_name_plural': '당직 템플릿',
                'ordering': ['name', 'department'],
            },
        ),
    ]
