# Generated by Django 5.2 on 2025-05-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_dutytemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DutyTemplate',
        ),
    ]
