# Generated by Django 5.2.1 on 2025-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_delete_dutytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='work_schedules', to='schedule.department', verbose_name='부서'),
        ),
    ]
